<?php

// UDP Social customization — inter-node pairing handshake endpoint
// SPDX-FileCopyrightText: 2010-2024 the Friendica project
// SPDX-License-Identifier: AGPL-3.0-or-later

namespace Friendica\Module\Udp;

use Friendica\BaseModule;
use Friendica\DI;
use Friendica\Util\Network;

/**
 * Called by Admin A's node to redeem a pairing token generated by Admin B's node.
 *
 * POST /udp/pair
 * Body (JSON): { "token": "<hex>", "requesting_domain": "node-a.udp.social" }
 * Response:    { "success": true, "domain": "node-b.udp.social" }
 *            | { "success": false, "error": "<reason>" }
 *
 * The token is single-use. On success both allowlists are updated:
 *   - this node adds requesting_domain to allowed_sites
 *   - the caller adds this node's domain (returned in response) to its own allowed_sites
 *
 * New file = zero upstream merge conflict risk.
 */
class PairEndpoint extends BaseModule
{
	protected function rawContent(array $request = []): void
	{
		if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
			$this->jsonExit(['success' => false, 'error' => 'POST required'], 'application/json', 405);
		}

		$body = Network::postdata();
		$data = json_decode($body, true);

		$token            = $data['token']            ?? '';
		$requesting_domain = $data['requesting_domain'] ?? '';

		if (!$token || !$requesting_domain) {
			$this->jsonExit(['success' => false, 'error' => 'missing token or requesting_domain'], 'application/json', 400);
		}

		// Validate the token
		$stored = DI::config()->get('udp_pair', $token);
		if (!$stored) {
			$this->jsonExit(['success' => false, 'error' => 'token not found'], 'application/json', 403);
		}

		$pair_data = json_decode($stored, true);
		if (empty($pair_data['expires_at']) || $pair_data['expires_at'] < time()) {
			DI::config()->delete('udp_pair', $token);
			$this->jsonExit(['success' => false, 'error' => 'token expired'], 'application/json', 403);
		}

		// Validate requesting_domain before touching any config
		if (!$this->isValidHostname($requesting_domain)) {
			$this->jsonExit(['success' => false, 'error' => 'invalid requesting_domain'], 'application/json', 400);
		}

		// Consume token — single-use unless flagged multi_use (group broadcast tokens)
		if (empty($pair_data['multi_use'])) {
			DI::config()->delete('udp_pair', $token);
		}

		// Add the requesting node to this node's allowlist
		$this->addToAllowedSites($requesting_domain);
		DI::federationGateway()->allow($requesting_domain, 'peer');

		// Generate a shared secret for HMAC-signed inter-node requests
		$secret = bin2hex(random_bytes(32));
		DI::config()->set('udp_shared_secret', $requesting_domain, $secret);

		$this->jsonExit(['success' => true, 'domain' => DI::baseUrl()->getHost(), 'secret' => $secret]);
	}

	private function addToAllowedSites(string $domain): void
	{
		$current = DI::config()->get('system', 'allowed_sites') ?? '';
		$domains = array_filter(array_map('trim', explode(',', $current)));
		if (!in_array($domain, $domains, true)) {
			$domains[] = $domain;
			DI::config()->set('system', 'allowed_sites', implode(',', $domains));
		}
	}

	private function isValidHostname(string $domain): bool
	{
		return (bool) preg_match('/^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$/', $domain);
	}
}
